[workspace]
resolver = "2"
members = [
  "crates/orchestrator",
  "crates/da_clients/da-client-interface",
  "crates/da_clients/ethereum",
  "crates/utils",
  "crates/settlement_clients/settlement-client-interface", "crates/da_clients/aptos",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Apoorv Sadana <@apoorvsadana>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]


num = { version = "0.4.1" }
ethereum-da-client = { path = "crates/da_clients/ethereum" }
aptos-da-client = { path = "crates/da_clients/aptos"}
async-trait = { version = "0.1.77" }
da-client-interface = { path = "crates/da_clients/da-client-interface" }
axum = { version = "0.7.4" }
axum-macros = { version = "0.4.1" }
color-eyre = { version = "0.6.2" }
dotenvy = { version = "0.15.7" }
futures = { version = "0.3.30" }
mongodb = { version = "2.8.1" }
omniqueue = { version = "0.2.0" }
rstest = { version = "0.18.2" }
serde = { version = "1.0.197" }
serde_json = { version = "1.0.114" }
starknet = { version = "0.9.0" }
thiserror = { version = "1.0.57" }
tokio = { version = "1.36.0" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
url = { version = "2.5.0" }
uuid = { version = "1.7.0" }
num-bigint = { version = "0.4.4" }
httpmock = { version = "0.7.0" }
utils = { path = "crates/utils" }
arc-swap = { version = "1.7.1" }
num-traits = "0.2"
lazy_static = "1.4.0"
aptos-sdk = { git = "https://github.com/Tranduy1dol/aptos-core", branch="zeroize_v1.7" }

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin", branch = "main"}
x25519-dalek = { git = "https://github.com/Tranduy1dol/x25519-dalek", branch = "zeroize_v1.7" }
