[package]
name = "ethereum-da-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "68952c0", features = [
  "consensus",
  "providers",
  "rpc-client",
  "transport-http",
  "network",
  "eips",
  "signers",
  "signer-wallet",
] }
async-trait = { workspace = true }
c-kzg = "1.0.0"
color-eyre = { workspace = true }
da-client-interface = { workspace = true }
dotenv = "0.15"
mockall = "0.12.1"
reqwest = { version = "0.12.3" }
rstest = { workspace = true }
serde = { version = "1.0.196", default-features = false, features = ["derive"] }
starknet = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
tokio-test = "*"
