[package]
name = "aptos-settlement-client"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
settlement-client-interface = { workspace = true }
utils = { workspace = true }
aptos-sdk = { workspace = true }
color-eyre = { workspace = true }
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "68952c0" }
url = "2.5.2"
once_cell = "1.19.0"
async-trait = { workspace = true }