[package]
name = "aptos-da-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "68952c0" }
c-kzg = "1.0.2"
color-eyre = "0.6.3"
dotenv = "0.15.0"
url = "2.5.0"

aptos-sdk = { workspace = true }
async-trait = { workspace = true }
da-client-interface = { workspace = true }
serde = { workspace = true }
utils = { workspace = true }
