---
name: Task - Linters Cargo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2
      - name: Format and clippy
        run: |
          sudo apt install build-essential cmake pkg-config libudev-dev
          RUSTFLAGS="--cfg tokio_unstable" cargo fmt -- --check
          RUSTFLAGS="--cfg tokio_unstable" cargo clippy --no-deps -- -D warnings
          RUSTFLAGS="--cfg tokio_unstable" cargo clippy --tests --no-deps -- -D warnings
